### ISSUE TITLE
Figure out how to use DMA

### ISSUE THREAD

**Issue by eirikvaa** [NTNU-TDT4295/BRICOLEUR#18]

**Comment by Mkohm** [comment]
Using this video http://www.fpgadeveloper.com/2018/03/how-to-accelerate-a-python-function-with-pynq.html to understand how to communicate with the DMA. Can be a nice start to get it working in the same way as the video first, then modify the block diagram to so that we dont send input from our python code, but receives pixels directly from the "Video Test Pattern Generator - pre made block in Vivado"
